version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DsB6rYRpRF7.y7bw

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - db

  #frontend:
  #  container_name: react-app
  #  build: ./frontend
  #  volumes:
  #    - './:/app'
  #    - '/app/node_modules'
  #  ports:
  #    - 3000:3000
  #  stdin_open: true
  #  environment:
  #    - CHOKIDAR_USEPOLLING=true
  #  command: npm start
